### ISSUE TITLE
Update for release 1.1.37

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/dotnet-collections#17]

**Comment by darkl** [comment]
:+1: 

Any estimate when will this be done? I've been [requested](https://github.com/Code-Sharp/WampSharp-docs/issues/1) to update System.Collection.Immutable to 1.1.37, but Rackspace (.NET40 fallback) is still 1.1.36.

Thanks!

**Comment by darkl** [comment]
Also please let me know if I can help in any way.

**Comment by sharwell** [comment]
@darkl Are you still blocked on this? I was planning to delay the update until after a version with the fix for dotnet/corefx#3880 makes its way to a stable release.

**Comment by darkl** [comment]
Hi @sharwell, this isn't blocking me anymore.
Thanks

**Comment by sharwell** [comment]
I'm planning to wait for the next release (which includes more observable bug fixes) to update this library.
